# Site settings
title: Gallery of Undefined Behavior
email: someone@undefinedbehavior.org
description: > # this means to ignore newlines until "baseurl:"
  Exposition of examples of C and C++ undefined behavior that give interesting results in real-life compilers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://undefinedbehavior.org" # the base hostname & protocol for your site
github_username: govnocpp

# Build settings
markdown: kramdown
highlighter: pygments
exclude: [ CNAME, Gemfile, README.md ]

kramdown:
 input: GFM

